// Generated by https://quicktype.io
export interface ProductsTypes  {
	data?: ProductTypes[]
}

export interface ProductTypes {
	id:          number;
	title:       string;
	price:       number;
	description: string;
	category:    string;
	image:       string;
	rating:      Rating;
}


export interface Rating {
	rate:  number;	
	count: number;
}
